name: produce

on:
  workflow_dispatch:
    inputs:
      initfile:
        description: 'init file path'
        required: false
        type: string
        default: 'templet/init'
      deploydir:
        description: 'directory to place output files'
        required: true
        type: string
        default: 'produce'
      overwrite_spec:
        description: 'overwrite specific run, can only accept single <serial>, like 1'
        required: false
        type: string
      delete_spec:
        description: 'delete specific run, can accept multiple <serial>, like 1, 2, 3'
        required: false
        type: string
      overwrite_last:
        description: 'overwrite last run'
        required: false
        type: boolean
      delete_all:
        description: 'delete all runs'
        required: false
        type: boolean

jobs:
  produce:
    runs-on: ubuntu-latest
    env:
      REPO_PATH: test
      PRODUCE_DEVICE: ${{ secrets.PRODUCE_DEVICE }}
    steps:

    - uses: actions/checkout@v3
      if: env.PRODUCE_DEVICE != ''
      with:
        path: ${{ env.REPO_PATH }}
        token: ${{ env.PRODUCE_DEVICE }}

    - name: carry out
      if: env.PRODUCE_DEVICE != ''
      run: python ${{ env.REPO_PATH }}/templet/produce.py
      env:
        INITFILE: ${{ inputs.initfile }}
        DEPLOYDIR: ${{ inputs.deploydir }}
        OVERWRITE_LAST: ${{ inputs.overwrite_last }}
        OVERWRITE_SPEC: ${{ inputs.overwrite_spec }}
        DELETE_SPEC: ${{ inputs.delete_spec }}
        DELETE_ALL: ${{ inputs.delete_all }}

    - uses: stefanzweifel/git-auto-commit-action@v4
      if: env.PRODUCE_DEVICE != ''
      with:
        repository: ${{ env.REPO_PATH }}
        commit_message: device deployment changed
        commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

    - name: lack token print
      if: env.PRODUCE_DEVICE == ''
      run: echo 'Have no token, workflow exits!'
